/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateBillsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRecord"
      | "confidentialProtocolId"
      | "getMyBalance"
      | "getMyMonthlyExpense"
      | "getMyMonthlyExpenseByTag"
      | "getMyMonthlyIncomeByTag"
      | "getMyMonthlyNet"
      | "getMyRecordAmount"
      | "getMyRecordCount"
      | "getMyRecordMeta"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addRecord",
    values: [BytesLike, BytesLike, boolean, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyMonthlyExpense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyMonthlyExpenseByTag",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyMonthlyIncomeByTag",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyMonthlyNet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyRecordAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyRecordMeta",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyMonthlyExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyMonthlyExpenseByTag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyMonthlyIncomeByTag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyMonthlyNet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyRecordAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyRecordMeta",
    data: BytesLike
  ): Result;
}

export interface PrivateBills extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateBills;
  waitForDeployment(): Promise<this>;

  interface: PrivateBillsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecord: TypedContractMethod<
    [
      inputEuint64: BytesLike,
      inputProof: BytesLike,
      isIncome: boolean,
      timestamp: BigNumberish,
      tag: string,
      monthKey: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMyBalance: TypedContractMethod<[], [string], "view">;

  getMyMonthlyExpense: TypedContractMethod<
    [monthKey: BigNumberish],
    [string],
    "view"
  >;

  getMyMonthlyExpenseByTag: TypedContractMethod<
    [monthKey: BigNumberish, tag: string],
    [string],
    "view"
  >;

  getMyMonthlyIncomeByTag: TypedContractMethod<
    [monthKey: BigNumberish, tag: string],
    [string],
    "view"
  >;

  getMyMonthlyNet: TypedContractMethod<
    [monthKey: BigNumberish],
    [string],
    "view"
  >;

  getMyRecordAmount: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getMyRecordCount: TypedContractMethod<[], [bigint], "view">;

  getMyRecordMeta: TypedContractMethod<
    [index: BigNumberish],
    [
      [boolean, bigint, string, bigint] & {
        isIncome: boolean;
        timestamp: bigint;
        tag: string;
        monthKey: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecord"
  ): TypedContractMethod<
    [
      inputEuint64: BytesLike,
      inputProof: BytesLike,
      isIncome: boolean,
      timestamp: BigNumberish,
      tag: string,
      monthKey: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyBalance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyMonthlyExpense"
  ): TypedContractMethod<[monthKey: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMyMonthlyExpenseByTag"
  ): TypedContractMethod<
    [monthKey: BigNumberish, tag: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyMonthlyIncomeByTag"
  ): TypedContractMethod<
    [monthKey: BigNumberish, tag: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyMonthlyNet"
  ): TypedContractMethod<[monthKey: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMyRecordAmount"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMyRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyRecordMeta"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [boolean, bigint, string, bigint] & {
        isIncome: boolean;
        timestamp: bigint;
        tag: string;
        monthKey: bigint;
      }
    ],
    "view"
  >;

  filters: {};
}
